<?php

namespace AppBundle\Repository;

/**
 * EmailNewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailNewsletterRepository extends \Doctrine\ORM\EntityRepository
{
}
