<?php

namespace AppBundle\Repository;

/**
 * EmailNewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailNewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRegisteredByLike($term)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('n')
            ->from('AppBundle:EmailNewsletter', 'n')
            ->Where('n.email LIKE :terms')
            ->setParameter('terms', '%' . $term .'%' );
        return $qb->getQuery()->getResult();
    }
}
