<?php

namespace AppBundle\Repository;

/**
 * ListeEmailNewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeEmailNewsletterRepository extends \Doctrine\ORM\EntityRepository
{
}
