<?php

namespace AppBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllNewsletterDesc()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.datePublished', 'DESC');
        return $qb->getQuery()->getResult();
    }

}
